// AUTO-GENERATED by scripts/generate-api.mjs from openapi.json (TCG Shop API v1).
// Do not edit by hand: run `npm run generate:api` instead.

// ---- Schemas ----

export interface UpdateProfileRequest {
  name: string;
}

export interface UserResponse {
  id?: number;
  email?: string;
  name?: string;
  role?: "CUSTOMER" | "ADMIN";
  createdAt?: string;
}

export interface ChangePasswordRequest {
  currentPassword: string;
  newPassword: string;
}

export interface AuthResponse {
  /** JWT; send it as `Authorization: Bearer <token>` */
  token?: string;
  tokenType?: string;
  expiresAt?: string;
  user?: UserResponse;
}

export interface AddressRequest {
  /** Recipient name printed on the shipping label */
  fullName: string;
  line1: string;
  line2?: string;
  city: string;
  postalCode: string;
  country: "AT" | "BE" | "BG" | "HR" | "CY" | "CZ" | "DK" | "EE" | "FI" | "FR" | "DE" | "GR" | "HU" | "IE" | "IT" | "LV" | "LT" | "LU" | "MT" | "NL" | "PL" | "PT" | "RO" | "SK" | "SI" | "ES" | "SE";
  /** Make this the default address. The first address is always the default; the default moves only when another address is marked as default. */
  isDefault?: boolean;
}

export interface AddressResponse {
  id?: number;
  fullName?: string;
  line1?: string;
  line2?: string;
  city?: string;
  postalCode?: string;
  country?: "AT" | "BE" | "BG" | "HR" | "CY" | "CZ" | "DK" | "EE" | "FI" | "FR" | "DE" | "GR" | "HU" | "IE" | "IT" | "LV" | "LT" | "LU" | "MT" | "NL" | "PL" | "PT" | "RO" | "SK" | "SI" | "ES" | "SE";
  isDefault?: boolean;
}

export interface YuGiOhCardVariantRequest {
  rarity: "COMMON" | "RARE" | "SUPER_RARE" | "ULTRA_RARE" | "SECRET_RARE" | "ULTIMATE_RARE" | "GHOST_RARE" | "GOLD_RARE" | "STARLIGHT_RARE" | "COLLECTORS_RARE" | "PRISMATIC_SECRET_RARE" | "PLATINUM_SECRET_RARE" | "QUARTER_CENTURY_SECRET_RARE";
  condition: "NM" | "LP" | "MP" | "HP" | "DMG";
  setCode: string;
  cardNumber: string;
  stockQuantity: number;
  price: number;
}

export interface YuGiOhCardVariantResponse {
  id?: number;
  productId?: number;
  variantType?: "YU_GI_OH" | "POKEMON" | "ONE_PIECE";
  rarity?: "COMMON" | "RARE" | "SUPER_RARE" | "ULTRA_RARE" | "SECRET_RARE" | "ULTIMATE_RARE" | "GHOST_RARE" | "GOLD_RARE" | "STARLIGHT_RARE" | "COLLECTORS_RARE" | "PRISMATIC_SECRET_RARE" | "PLATINUM_SECRET_RARE" | "QUARTER_CENTURY_SECRET_RARE";
  condition?: "NM" | "LP" | "MP" | "HP" | "DMG";
  setCode?: string;
  cardNumber?: string;
  stockQuantity?: number;
  price?: number;
}

export interface PokemonCardVariantRequest {
  rarity: "COMMON" | "UNCOMMON" | "RARE" | "DOUBLE_RARE" | "ULTRA_RARE" | "ILLUSTRATION_RARE" | "SPECIAL_ILLUSTRATION_RARE" | "HYPER_RARE" | "SHINY_RARE" | "ACE_SPEC_RARE" | "PROMO";
  holoType: "NON_HOLO" | "HOLO" | "REVERSE_HOLO" | "FULL_ART" | "ALT_ART";
  condition: "NM" | "LP" | "MP" | "HP" | "DMG";
  setCode: string;
  cardNumber: string;
  stockQuantity: number;
  price: number;
}

export interface PokemonCardVariantResponse {
  id?: number;
  productId?: number;
  variantType?: "YU_GI_OH" | "POKEMON" | "ONE_PIECE";
  rarity?: "COMMON" | "UNCOMMON" | "RARE" | "DOUBLE_RARE" | "ULTRA_RARE" | "ILLUSTRATION_RARE" | "SPECIAL_ILLUSTRATION_RARE" | "HYPER_RARE" | "SHINY_RARE" | "ACE_SPEC_RARE" | "PROMO";
  holoType?: "NON_HOLO" | "HOLO" | "REVERSE_HOLO" | "FULL_ART" | "ALT_ART";
  condition?: "NM" | "LP" | "MP" | "HP" | "DMG";
  setCode?: string;
  cardNumber?: string;
  stockQuantity?: number;
  price?: number;
}

export interface OnePieceCardVariantRequest {
  rarity: "C" | "UC" | "R" | "SR" | "SEC" | "L" | "SP" | "P";
  cardType: "LEADER" | "CHARACTER" | "EVENT" | "STAGE";
  condition: "NM" | "LP" | "MP" | "HP" | "DMG";
  setCode: string;
  cardNumber: string;
  stockQuantity: number;
  price: number;
}

export interface OnePieceCardVariantResponse {
  id?: number;
  productId?: number;
  variantType?: "YU_GI_OH" | "POKEMON" | "ONE_PIECE";
  rarity?: "C" | "UC" | "R" | "SR" | "SEC" | "L" | "SP" | "P";
  cardType?: "LEADER" | "CHARACTER" | "EVENT" | "STAGE";
  condition?: "NM" | "LP" | "MP" | "HP" | "DMG";
  setCode?: string;
  cardNumber?: string;
  stockQuantity?: number;
  price?: number;
}

export interface ProductRequest {
  gameId: number;
  /** Must belong to the same game */
  categoryId: number;
  productType: "SEALED" | "SINGLE" | "ACCESSORY";
  name: string;
  description?: string;
  /** URL slug, unique within the game. When omitted: derived from the name on create, unchanged on update. */
  slug?: string;
  /** Set the product belongs to (stored upper-case) */
  setCode?: string;
  /** EUR incl. VAT. Required for SEALED and ACCESSORY; ignored for SINGLE, whose price comes from its card variants. */
  basePrice?: number;
  imageUrls?: string[];
  preorder?: boolean;
  /** Expected release date; required when preorder is true */
  releaseDate?: string;
  /** Required for SEALED and ACCESSORY; ignored for SINGLE (sum of its variants). For pre-orders: how many units can still be pre-ordered. */
  stockQuantity?: number;
}

export interface ProductResponse {
  id?: number;
  gameId?: number;
  categoryId?: number;
  productType?: "SEALED" | "SINGLE" | "ACCESSORY";
  name?: string;
  description?: string;
  slug?: string;
  setCode?: string;
  /** EUR incl. VAT. For singles: the cheapest in-stock variant ("from" price). */
  basePrice?: number;
  imageUrls?: string[];
  preorder?: boolean;
  releaseDate?: string;
  /** Units available. For singles: sum of all variants. For pre-orders: remaining pre-order allocation. */
  stockQuantity?: number;
  /** Derived from preorder and stockQuantity */
  availability?: "IN_STOCK" | "PREORDER" | "OUT_OF_STOCK";
  createdAt?: string;
}

export interface GameRequest {
  name: "YU_GI_OH" | "POKEMON" | "ONE_PIECE";
  /** URL slug. When omitted: the game's standard slug on create, unchanged on update. */
  slug?: string;
}

export interface GameResponse {
  id?: number;
  name?: "YU_GI_OH" | "POKEMON" | "ONE_PIECE";
  displayName?: string;
  slug?: string;
}

export interface CategoryRequest {
  gameId: number;
  name: string;
  /** URL slug, unique within the game. When omitted: derived from the name on create, unchanged on update. */
  slug?: string;
  /** Parent category for a subcategory; must belong to the same game. Null for a top-level category. */
  parentCategoryId?: number;
}

export interface CategoryResponse {
  id?: number;
  gameId?: number;
  name?: string;
  slug?: string;
  parentCategoryId?: number;
}

export interface UpdateCartItemRequest {
  quantity: number;
}

export interface CartLineResponse {
  id?: number;
  productId?: number;
  productName?: string;
  productSlug?: string;
  gameSlug?: string;
  imageUrl?: string;
  variantType?: "YU_GI_OH" | "POKEMON" | "ONE_PIECE";
  variantId?: number;
  /** Summary of the card variant, e.g. "LOB-EN 001 · SECRET_RARE · NM" */
  variantDescription?: string;
  quantity?: number;
  /** Current price (EUR incl. VAT); null if the item no longer exists */
  unitPrice?: number;
  lineTotal?: number;
  preorder?: boolean;
  releaseDate?: string;
  /** Units currently available (pre-orders: remaining allocation) */
  availableStock?: number;
  /** Why this line cannot be checked out, e.g. "Out of stock"; null if it can */
  problem?: string | null;
}

export interface CartResponse {
  items?: CartLineResponse[];
  /** Total units across all lines */
  itemCount?: number;
  subtotal?: number;
  /** Country of the shipping estimate; null unless `country` was requested */
  shippingCountry?: "AT" | "BE" | "BG" | "HR" | "CY" | "CZ" | "DK" | "EE" | "FI" | "FR" | "DE" | "GR" | "HU" | "IE" | "IT" | "LV" | "LT" | "LU" | "MT" | "NL" | "PL" | "PT" | "RO" | "SK" | "SI" | "ES" | "SE";
  /** Shipping estimate; null unless `country` was requested */
  shippingCost?: number;
  /** Subtotal plus shipping estimate (subtotal only without `country`) */
  total?: number;
  containsPreorders?: boolean;
  /** True if the cart is not empty and no line has a problem */
  checkoutReady?: boolean;
}

export interface ShippingRateRequest {
  price: number;
  /** Order subtotal from which shipping is free; null means never free */
  freeShippingThreshold?: number | null;
}

export interface ShippingRateResponse {
  country?: "AT" | "BE" | "BG" | "HR" | "CY" | "CZ" | "DK" | "EE" | "FI" | "FR" | "DE" | "GR" | "HU" | "IE" | "IT" | "LV" | "LT" | "LU" | "MT" | "NL" | "PL" | "PT" | "RO" | "SK" | "SI" | "ES" | "SE";
  countryName?: string;
  price?: number;
  freeShippingThreshold?: number;
}

export interface UpdateShipmentRequest {
  carrier: string;
  trackingNumber: string;
}

export interface OrderItemResponse {
  id?: number;
  productId?: number;
  productName?: string;
  variantType?: "YU_GI_OH" | "POKEMON" | "ONE_PIECE";
  variantId?: number;
  variantDescription?: string;
  quantity?: number;
  priceAtPurchase?: number;
  lineTotal?: number;
  preorder?: boolean;
  releaseDate?: string;
  fulfillmentStatus?: "PENDING_PAYMENT" | "READY_TO_SHIP" | "AWAITING_STOCK" | "SHIPPED" | "DELIVERED" | "CANCELLED";
  shipmentId?: number;
}

export interface OrderResponse {
  id?: number;
  orderNumber?: string;
  status?: "PENDING_PAYMENT" | "PAID" | "AWAITING_STOCK" | "PARTIALLY_SHIPPED" | "SHIPPED" | "DELIVERED" | "CANCELLED";
  customerEmail?: string;
  customerName?: string;
  shippingAddress?: ShippingAddressResponse;
  items?: OrderItemResponse[];
  shipments?: ShipmentResponse[];
  subtotal?: number;
  shippingCost?: number;
  totalAmount?: number;
  currency?: string;
  paymentProvider?: "STRIPE" | "PAYPAL";
  createdAt?: string;
  /** When the order is cancelled if still unpaid; null once paid or cancelled */
  paymentDueBy?: string | null;
  paidAt?: string;
  cancelledAt?: string;
}

export interface ShipmentResponse {
  id?: number;
  carrier?: string;
  trackingNumber?: string;
  shippedAt?: string;
  deliveredAt?: string;
  itemIds?: number[];
}

export interface ShippingAddressResponse {
  fullName?: string;
  line1?: string;
  line2?: string;
  city?: string;
  postalCode?: string;
  country?: "AT" | "BE" | "BG" | "HR" | "CY" | "CZ" | "DK" | "EE" | "FI" | "FR" | "DE" | "GR" | "HU" | "IE" | "IT" | "LV" | "LT" | "LU" | "MT" | "NL" | "PL" | "PT" | "RO" | "SK" | "SI" | "ES" | "SE";
}

export interface StartPaymentRequest {
  provider: "STRIPE" | "PAYPAL";
}

export interface PaymentStartResponse {
  paymentId?: number;
  provider?: "STRIPE" | "PAYPAL";
  amount?: number;
  currency?: string;
  /** STRIPE only: client secret for Stripe.js / Payment Element */
  stripeClientSecret?: string;
  /** PAYPAL only: PayPal order id, needed for the capture call */
  payPalOrderId?: string;
  /** PAYPAL only: redirect the buyer here to approve the payment */
  payPalApprovalUrl?: string;
}

export interface CapturePayPalRequest {
  /** PayPal order id: the `token` query parameter PayPal appends to the return URL */
  payPalOrderId: string;
}

export interface CheckoutRequest {
  /** One of the signed-in user's saved addresses; it is copied onto the order */
  addressId: number;
}

export interface CartItemRequest {
  productId: number;
  /** Required for singles (the product's game); omit for other products */
  variantType?: "YU_GI_OH" | "POKEMON" | "ONE_PIECE";
  /** Card variant id; required for singles, omit for other products */
  variantId?: number;
  /** Units to add to the cart */
  quantity: number;
}

export interface RegisterRequest {
  email: string;
  password: string;
  name: string;
}

export interface PasswordResetRequest {
  email: string;
}

export interface PasswordResetConfirmRequest {
  token: string;
  newPassword: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface PreorderReleaseResponse {
  productId?: number;
  /** Order items moved from AWAITING_STOCK to READY_TO_SHIP */
  itemsReadyToShip?: number;
  /** Orders containing those items */
  ordersAffected?: number;
}

export interface CreateShipmentRequest {
  carrier: string;
  trackingNumber: string;
  /** Order item ids in this parcel; all READY_TO_SHIP items when omitted */
  itemIds?: number[];
}

export interface PageResponseProductResponse {
  content?: ProductResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}

export interface OrderSummaryResponse {
  id?: number;
  orderNumber?: string;
  status?: "PENDING_PAYMENT" | "PAID" | "AWAITING_STOCK" | "PARTIALLY_SHIPPED" | "SHIPPED" | "DELIVERED" | "CANCELLED";
  customerEmail?: string;
  itemCount?: number;
  containsPreorders?: boolean;
  totalAmount?: number;
  currency?: string;
  createdAt?: string;
  paidAt?: string;
}

export interface PageResponseOrderSummaryResponse {
  content?: OrderSummaryResponse[];
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}

export interface PaymentResponse {
  id?: number;
  provider?: "STRIPE" | "PAYPAL";
  status?: "CREATED" | "SUCCEEDED" | "CANCELLED" | "REFUNDED" | "REFUND_FAILED";
  amount?: number;
  currency?: string;
  providerTransactionId?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface PreorderSummaryResponse {
  productId?: number;
  productName?: string;
  releaseDate?: string;
  /** False once the product has been released */
  stillPreorder?: boolean;
  /** Units that can still be pre-ordered (the product's stock) */
  remainingAllocation?: number;
  /** Paid units waiting for the product to be released */
  unitsAwaitingStock?: number;
  /** Orders containing those units */
  ordersAwaitingStock?: number;
}

export interface PreorderItemResponse {
  orderId?: number;
  orderNumber?: string;
  customerEmail?: string;
  orderItemId?: number;
  variantType?: "YU_GI_OH" | "POKEMON" | "ONE_PIECE";
  variantId?: number;
  quantity?: number;
  paidAt?: string;
}

export interface AdminOverviewResponse {
  currency?: string;
  today?: SalesPeriod;
  last30Days?: SalesPeriod;
  allTime?: SalesPeriod;
  ordersByStatus?: Record<string, number>;
  unitsReadyToShip?: number;
  preorderUnitsAwaitingStock?: number;
  outOfStockProducts?: number;
  lowStockThreshold?: number;
  lowStockProducts?: LowStockProduct[];
}

export interface LowStockProduct {
  id?: number;
  name?: string;
  productType?: "SEALED" | "SINGLE" | "ACCESSORY";
  stockQuantity?: number;
  availability?: "IN_STOCK" | "PREORDER" | "OUT_OF_STOCK";
}

export interface SalesPeriod {
  paidOrders?: number;
  revenue?: number;
}

/** Body of every error response */
export interface ErrorResponse {
  timestamp?: string;
  status?: number;
  /** HTTP reason phrase */
  error?: string;
  /** Human-readable explanation */
  message?: string;
  path?: string;
  /** Per-field validation messages; only present on validation errors (400) */
  fieldErrors?: FieldViolation[];
}

/** Per-field validation messages; only present on validation errors (400) */
export interface FieldViolation {
  field?: string;
  message?: string;
}

// ---- Operation parameters ----

/** Query parameters of `listCategories`. */
export interface ListCategoriesParams {
  /** Only categories of this game */
  gameId?: number;
}

/** Query parameters of `getCart`. */
export interface GetCartParams {
  /** Shipping country for a shipping cost estimate */
  country?: "AT" | "BE" | "BG" | "HR" | "CY" | "CZ" | "DK" | "EE" | "FI" | "FR" | "DE" | "GR" | "HU" | "IE" | "IT" | "LV" | "LT" | "LU" | "MT" | "NL" | "PL" | "PT" | "RO" | "SK" | "SI" | "ES" | "SE";
}

/** Query parameters of `listMyOrders`. */
export interface ListMyOrdersParams {
  /**
   * Zero-based page index (0..N)
   * @default 0
   */
  page?: number;
  /**
   * The size of the page to be returned
   * @default 20
   */
  size?: number;
  /** Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
  sort?: string[];
}

/** Query parameters of `searchProducts`. */
export interface SearchProductsParams {
  /** Game id */
  gameId?: number;
  /**
   * Game slug
   * @example "pokemon"
   */
  game?: string;
  /** Category id; includes all of its subcategories */
  categoryId?: number;
  /** Product type */
  type?: "SEALED" | "SINGLE" | "ACCESSORY";
  /**
   * Set code of the product itself or of any of its card variants (case-insensitive)
   * @example "SV3PT5"
   */
  setCode?: string;
  /** Rarity of any card variant (case-insensitive), e.g. SECRET_RARE or SEC. Unknown rarities are rejected with 400. */
  rarity?: string;
  /** Inclusive lower bound on basePrice (EUR) */
  minPrice?: number;
  /** Inclusive upper bound on basePrice (EUR) */
  maxPrice?: number;
  /** Availability */
  availability?: "IN_STOCK" | "PREORDER" | "OUT_OF_STOCK";
  /** Case-insensitive text contained in the product name */
  q?: string;
  /**
   * Zero-based page index (0..N)
   * @default 0
   */
  page?: number;
  /**
   * The size of the page to be returned
   * @default 20
   */
  size?: number;
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   * @default ["createdAt,DESC"]
   */
  sort?: string[];
}

/** Header parameters of `handleStripeWebhook`. */
export interface HandleStripeWebhookHeaders {
  "Stripe-Signature": string;
}

/** Query parameters of `searchAdminOrders`. */
export interface SearchAdminOrdersParams {
  status?: "PENDING_PAYMENT" | "PAID" | "AWAITING_STOCK" | "PARTIALLY_SHIPPED" | "SHIPPED" | "DELIVERED" | "CANCELLED";
  /** Partial, case-insensitive match on order number or customer email */
  q?: string;
  /**
   * Zero-based page index (0..N)
   * @default 0
   */
  page?: number;
  /**
   * The size of the page to be returned
   * @default 20
   */
  size?: number;
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   * @default ["createdAt,DESC"]
   */
  sort?: string[];
}
