// AUTO-GENERATED by scripts/generate-api.mjs from openapi.json (TCG Shop API v1).
// Do not edit by hand: run `npm run generate:api` instead.

export const UserResponseRoleValues = ["CUSTOMER","ADMIN"] as const;

export const AddressRequestCountryValues = ["AT","BE","BG","HR","CY","CZ","DK","EE","FI","FR","DE","GR","HU","IE","IT","LV","LT","LU","MT","NL","PL","PT","RO","SK","SI","ES","SE"] as const;

export const AddressResponseCountryValues = ["AT","BE","BG","HR","CY","CZ","DK","EE","FI","FR","DE","GR","HU","IE","IT","LV","LT","LU","MT","NL","PL","PT","RO","SK","SI","ES","SE"] as const;

export const YuGiOhCardVariantRequestRarityValues = ["COMMON","RARE","SUPER_RARE","ULTRA_RARE","SECRET_RARE","ULTIMATE_RARE","GHOST_RARE","GOLD_RARE","STARLIGHT_RARE","COLLECTORS_RARE","PRISMATIC_SECRET_RARE","PLATINUM_SECRET_RARE","QUARTER_CENTURY_SECRET_RARE"] as const;

export const YuGiOhCardVariantRequestConditionValues = ["NM","LP","MP","HP","DMG"] as const;

export const YuGiOhCardVariantResponseVariantTypeValues = ["YU_GI_OH","POKEMON","ONE_PIECE"] as const;

export const YuGiOhCardVariantResponseRarityValues = ["COMMON","RARE","SUPER_RARE","ULTRA_RARE","SECRET_RARE","ULTIMATE_RARE","GHOST_RARE","GOLD_RARE","STARLIGHT_RARE","COLLECTORS_RARE","PRISMATIC_SECRET_RARE","PLATINUM_SECRET_RARE","QUARTER_CENTURY_SECRET_RARE"] as const;

export const YuGiOhCardVariantResponseConditionValues = ["NM","LP","MP","HP","DMG"] as const;

export const PokemonCardVariantRequestRarityValues = ["COMMON","UNCOMMON","RARE","DOUBLE_RARE","ULTRA_RARE","ILLUSTRATION_RARE","SPECIAL_ILLUSTRATION_RARE","HYPER_RARE","SHINY_RARE","ACE_SPEC_RARE","PROMO"] as const;

export const PokemonCardVariantRequestHoloTypeValues = ["NON_HOLO","HOLO","REVERSE_HOLO","FULL_ART","ALT_ART"] as const;

export const PokemonCardVariantRequestConditionValues = ["NM","LP","MP","HP","DMG"] as const;

export const PokemonCardVariantResponseVariantTypeValues = ["YU_GI_OH","POKEMON","ONE_PIECE"] as const;

export const PokemonCardVariantResponseRarityValues = ["COMMON","UNCOMMON","RARE","DOUBLE_RARE","ULTRA_RARE","ILLUSTRATION_RARE","SPECIAL_ILLUSTRATION_RARE","HYPER_RARE","SHINY_RARE","ACE_SPEC_RARE","PROMO"] as const;

export const PokemonCardVariantResponseHoloTypeValues = ["NON_HOLO","HOLO","REVERSE_HOLO","FULL_ART","ALT_ART"] as const;

export const PokemonCardVariantResponseConditionValues = ["NM","LP","MP","HP","DMG"] as const;

export const OnePieceCardVariantRequestRarityValues = ["C","UC","R","SR","SEC","L","SP","P"] as const;

export const OnePieceCardVariantRequestCardTypeValues = ["LEADER","CHARACTER","EVENT","STAGE"] as const;

export const OnePieceCardVariantRequestConditionValues = ["NM","LP","MP","HP","DMG"] as const;

export const OnePieceCardVariantResponseVariantTypeValues = ["YU_GI_OH","POKEMON","ONE_PIECE"] as const;

export const OnePieceCardVariantResponseRarityValues = ["C","UC","R","SR","SEC","L","SP","P"] as const;

export const OnePieceCardVariantResponseCardTypeValues = ["LEADER","CHARACTER","EVENT","STAGE"] as const;

export const OnePieceCardVariantResponseConditionValues = ["NM","LP","MP","HP","DMG"] as const;

export const ProductRequestProductTypeValues = ["SEALED","SINGLE","ACCESSORY"] as const;

export const ProductResponseProductTypeValues = ["SEALED","SINGLE","ACCESSORY"] as const;

export const ProductResponseAvailabilityValues = ["IN_STOCK","PREORDER","OUT_OF_STOCK"] as const;

export const GameRequestNameValues = ["YU_GI_OH","POKEMON","ONE_PIECE"] as const;

export const GameResponseNameValues = ["YU_GI_OH","POKEMON","ONE_PIECE"] as const;

export const CartLineResponseVariantTypeValues = ["YU_GI_OH","POKEMON","ONE_PIECE"] as const;

export const CartResponseShippingCountryValues = ["AT","BE","BG","HR","CY","CZ","DK","EE","FI","FR","DE","GR","HU","IE","IT","LV","LT","LU","MT","NL","PL","PT","RO","SK","SI","ES","SE"] as const;

export const ShippingRateResponseCountryValues = ["AT","BE","BG","HR","CY","CZ","DK","EE","FI","FR","DE","GR","HU","IE","IT","LV","LT","LU","MT","NL","PL","PT","RO","SK","SI","ES","SE"] as const;

export const OrderItemResponseVariantTypeValues = ["YU_GI_OH","POKEMON","ONE_PIECE"] as const;

export const OrderItemResponseFulfillmentStatusValues = ["PENDING_PAYMENT","READY_TO_SHIP","AWAITING_STOCK","SHIPPED","DELIVERED","CANCELLED"] as const;

export const OrderResponseStatusValues = ["PENDING_PAYMENT","PAID","AWAITING_STOCK","PARTIALLY_SHIPPED","SHIPPED","DELIVERED","CANCELLED"] as const;

export const OrderResponsePaymentProviderValues = ["STRIPE","PAYPAL"] as const;

export const ShippingAddressResponseCountryValues = ["AT","BE","BG","HR","CY","CZ","DK","EE","FI","FR","DE","GR","HU","IE","IT","LV","LT","LU","MT","NL","PL","PT","RO","SK","SI","ES","SE"] as const;

export const StartPaymentRequestProviderValues = ["STRIPE","PAYPAL"] as const;

export const PaymentStartResponseProviderValues = ["STRIPE","PAYPAL"] as const;

export const CartItemRequestVariantTypeValues = ["YU_GI_OH","POKEMON","ONE_PIECE"] as const;

export const OrderSummaryResponseStatusValues = ["PENDING_PAYMENT","PAID","AWAITING_STOCK","PARTIALLY_SHIPPED","SHIPPED","DELIVERED","CANCELLED"] as const;

export const PaymentResponseProviderValues = ["STRIPE","PAYPAL"] as const;

export const PaymentResponseStatusValues = ["CREATED","SUCCEEDED","CANCELLED","REFUNDED","REFUND_FAILED"] as const;

export const PreorderItemResponseVariantTypeValues = ["YU_GI_OH","POKEMON","ONE_PIECE"] as const;

export const LowStockProductProductTypeValues = ["SEALED","SINGLE","ACCESSORY"] as const;

export const LowStockProductAvailabilityValues = ["IN_STOCK","PREORDER","OUT_OF_STOCK"] as const;
