// AUTO-GENERATED by scripts/generate-api.mjs from openapi.json (TCG Shop API v1).
// Do not edit by hand: run `npm run generate:api` instead.

import { apiRequest, type RequestOptions } from "./api-client";
import type {
  AddressRequest,
  AddressResponse,
  AdminOverviewResponse,
  AuthResponse,
  CapturePayPalRequest,
  CartItemRequest,
  CartResponse,
  CategoryRequest,
  CategoryResponse,
  ChangePasswordRequest,
  CheckoutRequest,
  CreateShipmentRequest,
  GameRequest,
  GameResponse,
  GetCartParams,
  HandleStripeWebhookHeaders,
  ListCategoriesParams,
  ListMyOrdersParams,
  LoginRequest,
  OnePieceCardVariantRequest,
  OnePieceCardVariantResponse,
  OrderResponse,
  PageResponseOrderSummaryResponse,
  PageResponseProductResponse,
  PasswordResetConfirmRequest,
  PasswordResetRequest,
  PaymentResponse,
  PaymentStartResponse,
  PokemonCardVariantRequest,
  PokemonCardVariantResponse,
  PreorderItemResponse,
  PreorderReleaseResponse,
  PreorderSummaryResponse,
  ProductRequest,
  ProductResponse,
  RegisterRequest,
  SearchAdminOrdersParams,
  SearchProductsParams,
  ShippingRateRequest,
  ShippingRateResponse,
  StartPaymentRequest,
  UpdateCartItemRequest,
  UpdateProfileRequest,
  UpdateShipmentRequest,
  UserResponse,
  YuGiOhCardVariantRequest,
  YuGiOhCardVariantResponse,
} from "@/types/api";

export { API_BASE_URL, ApiError, type RequestOptions } from "./api-client";

// ---- Categories ----

/** `GET /api/categories/{id}` · Public. */
export function getCategory(id: number, options?: RequestOptions): Promise<CategoryResponse> {
  return apiRequest<CategoryResponse>("GET", `/api/categories/${encodeURIComponent(String(id))}`, {}, options);
}

/** `PUT /api/categories/{id}` · Requires a bearer token (`options.token`). Requires the ADMIN role. */
export function updateCategory(id: number, body: CategoryRequest, options?: RequestOptions): Promise<CategoryResponse> {
  return apiRequest<CategoryResponse>("PUT", `/api/categories/${encodeURIComponent(String(id))}`, { body }, options);
}

/** `DELETE /api/categories/{id}` · Requires a bearer token (`options.token`). Requires the ADMIN role. */
export function deleteCategory(id: number, options?: RequestOptions): Promise<void> {
  return apiRequest<void>("DELETE", `/api/categories/${encodeURIComponent(String(id))}`, {}, options);
}

/** `GET /api/categories` · Public. */
export function listCategories(params?: ListCategoriesParams, options?: RequestOptions): Promise<CategoryResponse[]> {
  return apiRequest<CategoryResponse[]>("GET", "/api/categories", { query: params }, options);
}

/** `POST /api/categories` · Requires a bearer token (`options.token`). Requires the ADMIN role. */
export function createCategory(body: CategoryRequest, options?: RequestOptions): Promise<CategoryResponse> {
  return apiRequest<CategoryResponse>("POST", "/api/categories", { body }, options);
}

// ---- Card variants: One Piece ----

/** `GET /api/products/{productId}/one-piece-variants/{variantId}` · Public. */
export function getOnePieceVariant(productId: number, variantId: number, options?: RequestOptions): Promise<OnePieceCardVariantResponse> {
  return apiRequest<OnePieceCardVariantResponse>("GET", `/api/products/${encodeURIComponent(String(productId))}/one-piece-variants/${encodeURIComponent(String(variantId))}`, {}, options);
}

/** `PUT /api/products/{productId}/one-piece-variants/{variantId}` · Requires a bearer token (`options.token`). Requires the ADMIN role. */
export function updateOnePieceVariant(productId: number, variantId: number, body: OnePieceCardVariantRequest, options?: RequestOptions): Promise<OnePieceCardVariantResponse> {
  return apiRequest<OnePieceCardVariantResponse>("PUT", `/api/products/${encodeURIComponent(String(productId))}/one-piece-variants/${encodeURIComponent(String(variantId))}`, { body }, options);
}

/**
 * Delete a card variant
 *
 * Not possible once the variant has been ordered; set its stock to 0 instead.
 *
 * `DELETE /api/products/{productId}/one-piece-variants/{variantId}` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function deleteOnePieceVariant(productId: number, variantId: number, options?: RequestOptions): Promise<void> {
  return apiRequest<void>("DELETE", `/api/products/${encodeURIComponent(String(productId))}/one-piece-variants/${encodeURIComponent(String(variantId))}`, {}, options);
}

/**
 * List the card variants of a single
 *
 * `GET /api/products/{productId}/one-piece-variants` · Public.
 */
export function listOnePieceVariants(productId: number, options?: RequestOptions): Promise<OnePieceCardVariantResponse[]> {
  return apiRequest<OnePieceCardVariantResponse[]>("GET", `/api/products/${encodeURIComponent(String(productId))}/one-piece-variants`, {}, options);
}

/**
 * Add a card variant
 *
 * Only for SINGLE products of this game. Updates the product's "from" price and total stock.
 *
 * `POST /api/products/{productId}/one-piece-variants` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function createOnePieceVariant(productId: number, body: OnePieceCardVariantRequest, options?: RequestOptions): Promise<OnePieceCardVariantResponse> {
  return apiRequest<OnePieceCardVariantResponse>("POST", `/api/products/${encodeURIComponent(String(productId))}/one-piece-variants`, { body }, options);
}

// ---- Auth ----

/** `POST /api/auth/register` · Public. */
export function register(body: RegisterRequest, options?: RequestOptions): Promise<AuthResponse> {
  return apiRequest<AuthResponse>("POST", "/api/auth/register", { body }, options);
}

/**
 * Request a password reset link
 *
 * Always answers 202, whether or not the email belongs to an account, so accounts cannot be enumerated. The link is valid for one hour.
 *
 * `POST /api/auth/password-reset/request` · Public.
 */
export function requestPasswordReset(body: PasswordResetRequest, options?: RequestOptions): Promise<void> {
  return apiRequest<void>("POST", "/api/auth/password-reset/request", { body }, options);
}

/**
 * Set a new password with a reset token
 *
 * The token is single-use. Tokens issued before the reset stop working.
 *
 * `POST /api/auth/password-reset/confirm` · Public.
 */
export function confirmPasswordReset(body: PasswordResetConfirmRequest, options?: RequestOptions): Promise<void> {
  return apiRequest<void>("POST", "/api/auth/password-reset/confirm", { body }, options);
}

/** `POST /api/auth/login` · Public. */
export function login(body: LoginRequest, options?: RequestOptions): Promise<AuthResponse> {
  return apiRequest<AuthResponse>("POST", "/api/auth/login", { body }, options);
}

// ---- Addresses ----

/** `GET /api/users/me/addresses/{id}` · Requires a bearer token (`options.token`). */
export function getAddress(id: number, options?: RequestOptions): Promise<AddressResponse> {
  return apiRequest<AddressResponse>("GET", `/api/users/me/addresses/${encodeURIComponent(String(id))}`, {}, options);
}

/** `PUT /api/users/me/addresses/{id}` · Requires a bearer token (`options.token`). */
export function updateAddress(id: number, body: AddressRequest, options?: RequestOptions): Promise<AddressResponse> {
  return apiRequest<AddressResponse>("PUT", `/api/users/me/addresses/${encodeURIComponent(String(id))}`, { body }, options);
}

/** `DELETE /api/users/me/addresses/{id}` · Requires a bearer token (`options.token`). */
export function deleteAddress(id: number, options?: RequestOptions): Promise<void> {
  return apiRequest<void>("DELETE", `/api/users/me/addresses/${encodeURIComponent(String(id))}`, {}, options);
}

/** `GET /api/users/me/addresses` · Requires a bearer token (`options.token`). */
export function listAddresses(options?: RequestOptions): Promise<AddressResponse[]> {
  return apiRequest<AddressResponse[]>("GET", "/api/users/me/addresses", {}, options);
}

/** `POST /api/users/me/addresses` · Requires a bearer token (`options.token`). */
export function createAddress(body: AddressRequest, options?: RequestOptions): Promise<AddressResponse> {
  return apiRequest<AddressResponse>("POST", "/api/users/me/addresses", { body }, options);
}

// ---- Shipping rates ----

/** `GET /api/shipping-rates` · Public. */
export function listShippingRates(options?: RequestOptions): Promise<ShippingRateResponse[]> {
  return apiRequest<ShippingRateResponse[]>("GET", "/api/shipping-rates", {}, options);
}

/** `GET /api/shipping-rates/{country}` · Public. */
export function getShippingRate(country: "AT" | "BE" | "BG" | "HR" | "CY" | "CZ" | "DK" | "EE" | "FI" | "FR" | "DE" | "GR" | "HU" | "IE" | "IT" | "LV" | "LT" | "LU" | "MT" | "NL" | "PL" | "PT" | "RO" | "SK" | "SI" | "ES" | "SE", options?: RequestOptions): Promise<ShippingRateResponse> {
  return apiRequest<ShippingRateResponse>("GET", `/api/shipping-rates/${encodeURIComponent(String(country))}`, {}, options);
}

// ---- Cart ----

/** `PUT /api/cart/items/{itemId}` · Requires a bearer token (`options.token`). */
export function updateCartItem(itemId: number, body: UpdateCartItemRequest, options?: RequestOptions): Promise<CartResponse> {
  return apiRequest<CartResponse>("PUT", `/api/cart/items/${encodeURIComponent(String(itemId))}`, { body }, options);
}

/** `DELETE /api/cart/items/{itemId}` · Requires a bearer token (`options.token`). */
export function removeCartItem(itemId: number, options?: RequestOptions): Promise<CartResponse> {
  return apiRequest<CartResponse>("DELETE", `/api/cart/items/${encodeURIComponent(String(itemId))}`, {}, options);
}

/**
 * Add an item
 *
 * Merges with an existing line for the same product and variant.
 *
 * `POST /api/cart/items` · Requires a bearer token (`options.token`).
 */
export function addCartItem(body: CartItemRequest, options?: RequestOptions): Promise<CartResponse> {
  return apiRequest<CartResponse>("POST", "/api/cart/items", { body }, options);
}

/**
 * Get the cart
 *
 * Lines that can no longer be bought as-is carry a `problem`.
 *
 * `GET /api/cart` · Requires a bearer token (`options.token`).
 */
export function getCart(params?: GetCartParams, options?: RequestOptions): Promise<CartResponse> {
  return apiRequest<CartResponse>("GET", "/api/cart", { query: params }, options);
}

/** `DELETE /api/cart` · Requires a bearer token (`options.token`). */
export function clearCart(options?: RequestOptions): Promise<void> {
  return apiRequest<void>("DELETE", "/api/cart", {}, options);
}

// ---- Orders ----

/**
 * Cancel an unpaid order
 *
 * Releases the reserved stock.
 *
 * `POST /api/orders/{id}/cancel` · Requires a bearer token (`options.token`).
 */
export function cancelMyOrder(id: number, options?: RequestOptions): Promise<OrderResponse> {
  return apiRequest<OrderResponse>("POST", `/api/orders/${encodeURIComponent(String(id))}/cancel`, {}, options);
}

/**
 * Place an order from the cart
 *
 * Fixes prices, reserves stock and empties the cart. The order must be paid (see Payments) before `paymentDueBy`, otherwise it is cancelled and the stock released.
 *
 * `POST /api/orders/checkout` · Requires a bearer token (`options.token`).
 */
export function checkout(body: CheckoutRequest, options?: RequestOptions): Promise<OrderResponse> {
  return apiRequest<OrderResponse>("POST", "/api/orders/checkout", { body }, options);
}

/**
 * Order history
 *
 * Newest first, including orders with pending pre-order items. Client sort parameters are ignored.
 *
 * `GET /api/orders` · Requires a bearer token (`options.token`).
 */
export function listMyOrders(params?: ListMyOrdersParams, options?: RequestOptions): Promise<PageResponseOrderSummaryResponse> {
  return apiRequest<PageResponseOrderSummaryResponse>("GET", "/api/orders", { query: params }, options);
}

/** `GET /api/orders/{id}` · Requires a bearer token (`options.token`). */
export function getMyOrder(id: number, options?: RequestOptions): Promise<OrderResponse> {
  return apiRequest<OrderResponse>("GET", `/api/orders/${encodeURIComponent(String(id))}`, {}, options);
}

// ---- Card variants: Yu-Gi-Oh ----

/** `GET /api/products/{productId}/yugioh-variants/{variantId}` · Public. */
export function getYuGiOhVariant(productId: number, variantId: number, options?: RequestOptions): Promise<YuGiOhCardVariantResponse> {
  return apiRequest<YuGiOhCardVariantResponse>("GET", `/api/products/${encodeURIComponent(String(productId))}/yugioh-variants/${encodeURIComponent(String(variantId))}`, {}, options);
}

/** `PUT /api/products/{productId}/yugioh-variants/{variantId}` · Requires a bearer token (`options.token`). Requires the ADMIN role. */
export function updateYuGiOhVariant(productId: number, variantId: number, body: YuGiOhCardVariantRequest, options?: RequestOptions): Promise<YuGiOhCardVariantResponse> {
  return apiRequest<YuGiOhCardVariantResponse>("PUT", `/api/products/${encodeURIComponent(String(productId))}/yugioh-variants/${encodeURIComponent(String(variantId))}`, { body }, options);
}

/**
 * Delete a card variant
 *
 * Not possible once the variant has been ordered; set its stock to 0 instead.
 *
 * `DELETE /api/products/{productId}/yugioh-variants/{variantId}` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function deleteYuGiOhVariant(productId: number, variantId: number, options?: RequestOptions): Promise<void> {
  return apiRequest<void>("DELETE", `/api/products/${encodeURIComponent(String(productId))}/yugioh-variants/${encodeURIComponent(String(variantId))}`, {}, options);
}

/**
 * List the card variants of a single
 *
 * `GET /api/products/{productId}/yugioh-variants` · Public.
 */
export function listYuGiOhVariants(productId: number, options?: RequestOptions): Promise<YuGiOhCardVariantResponse[]> {
  return apiRequest<YuGiOhCardVariantResponse[]>("GET", `/api/products/${encodeURIComponent(String(productId))}/yugioh-variants`, {}, options);
}

/**
 * Add a card variant
 *
 * Only for SINGLE products of this game. Updates the product's "from" price and total stock.
 *
 * `POST /api/products/{productId}/yugioh-variants` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function createYuGiOhVariant(productId: number, body: YuGiOhCardVariantRequest, options?: RequestOptions): Promise<YuGiOhCardVariantResponse> {
  return apiRequest<YuGiOhCardVariantResponse>("POST", `/api/products/${encodeURIComponent(String(productId))}/yugioh-variants`, { body }, options);
}

// ---- Games ----

/** `GET /api/games/{id}` · Public. */
export function getGame(id: number, options?: RequestOptions): Promise<GameResponse> {
  return apiRequest<GameResponse>("GET", `/api/games/${encodeURIComponent(String(id))}`, {}, options);
}

/** `PUT /api/games/{id}` · Requires a bearer token (`options.token`). Requires the ADMIN role. */
export function updateGame(id: number, body: GameRequest, options?: RequestOptions): Promise<GameResponse> {
  return apiRequest<GameResponse>("PUT", `/api/games/${encodeURIComponent(String(id))}`, { body }, options);
}

/** `DELETE /api/games/{id}` · Requires a bearer token (`options.token`). Requires the ADMIN role. */
export function deleteGame(id: number, options?: RequestOptions): Promise<void> {
  return apiRequest<void>("DELETE", `/api/games/${encodeURIComponent(String(id))}`, {}, options);
}

/** `GET /api/games` · Public. */
export function listGames(options?: RequestOptions): Promise<GameResponse[]> {
  return apiRequest<GameResponse[]>("GET", "/api/games", {}, options);
}

/** `POST /api/games` · Requires a bearer token (`options.token`). Requires the ADMIN role. */
export function createGame(body: GameRequest, options?: RequestOptions): Promise<GameResponse> {
  return apiRequest<GameResponse>("POST", "/api/games", { body }, options);
}

/** `GET /api/games/slug/{slug}` · Public. */
export function getGameBySlug(slug: string, options?: RequestOptions): Promise<GameResponse> {
  return apiRequest<GameResponse>("GET", `/api/games/slug/${encodeURIComponent(String(slug))}`, {}, options);
}

// ---- Card variants: Pokémon ----

/** `GET /api/products/{productId}/pokemon-variants/{variantId}` · Public. */
export function getPokemonVariant(productId: number, variantId: number, options?: RequestOptions): Promise<PokemonCardVariantResponse> {
  return apiRequest<PokemonCardVariantResponse>("GET", `/api/products/${encodeURIComponent(String(productId))}/pokemon-variants/${encodeURIComponent(String(variantId))}`, {}, options);
}

/** `PUT /api/products/{productId}/pokemon-variants/{variantId}` · Requires a bearer token (`options.token`). Requires the ADMIN role. */
export function updatePokemonVariant(productId: number, variantId: number, body: PokemonCardVariantRequest, options?: RequestOptions): Promise<PokemonCardVariantResponse> {
  return apiRequest<PokemonCardVariantResponse>("PUT", `/api/products/${encodeURIComponent(String(productId))}/pokemon-variants/${encodeURIComponent(String(variantId))}`, { body }, options);
}

/**
 * Delete a card variant
 *
 * Not possible once the variant has been ordered; set its stock to 0 instead.
 *
 * `DELETE /api/products/{productId}/pokemon-variants/{variantId}` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function deletePokemonVariant(productId: number, variantId: number, options?: RequestOptions): Promise<void> {
  return apiRequest<void>("DELETE", `/api/products/${encodeURIComponent(String(productId))}/pokemon-variants/${encodeURIComponent(String(variantId))}`, {}, options);
}

/**
 * List the card variants of a single
 *
 * `GET /api/products/{productId}/pokemon-variants` · Public.
 */
export function listPokemonVariants(productId: number, options?: RequestOptions): Promise<PokemonCardVariantResponse[]> {
  return apiRequest<PokemonCardVariantResponse[]>("GET", `/api/products/${encodeURIComponent(String(productId))}/pokemon-variants`, {}, options);
}

/**
 * Add a card variant
 *
 * Only for SINGLE products of this game. Updates the product's "from" price and total stock.
 *
 * `POST /api/products/{productId}/pokemon-variants` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function createPokemonVariant(productId: number, body: PokemonCardVariantRequest, options?: RequestOptions): Promise<PokemonCardVariantResponse> {
  return apiRequest<PokemonCardVariantResponse>("POST", `/api/products/${encodeURIComponent(String(productId))}/pokemon-variants`, { body }, options);
}

// ---- Profile ----

/** `GET /api/users/me` · Requires a bearer token (`options.token`). */
export function getProfile(options?: RequestOptions): Promise<UserResponse> {
  return apiRequest<UserResponse>("GET", "/api/users/me", {}, options);
}

/** `PUT /api/users/me` · Requires a bearer token (`options.token`). */
export function updateProfile(body: UpdateProfileRequest, options?: RequestOptions): Promise<UserResponse> {
  return apiRequest<UserResponse>("PUT", "/api/users/me", { body }, options);
}

/**
 * Change password
 *
 * Returns a new token: tokens issued before the change are no longer accepted.
 *
 * `PUT /api/users/me/password` · Requires a bearer token (`options.token`).
 */
export function changePassword(body: ChangePasswordRequest, options?: RequestOptions): Promise<AuthResponse> {
  return apiRequest<AuthResponse>("PUT", "/api/users/me/password", { body }, options);
}

// ---- Products ----

/** `GET /api/products/{id}` · Public. */
export function getProduct(id: number, options?: RequestOptions): Promise<ProductResponse> {
  return apiRequest<ProductResponse>("GET", `/api/products/${encodeURIComponent(String(id))}`, {}, options);
}

/** `PUT /api/products/{id}` · Requires a bearer token (`options.token`). Requires the ADMIN role. */
export function updateProduct(id: number, body: ProductRequest, options?: RequestOptions): Promise<ProductResponse> {
  return apiRequest<ProductResponse>("PUT", `/api/products/${encodeURIComponent(String(id))}`, { body }, options);
}

/**
 * Delete a product
 *
 * Not possible once the product has been ordered; set its stock to 0 instead.
 *
 * `DELETE /api/products/{id}` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function deleteProduct(id: number, options?: RequestOptions): Promise<void> {
  return apiRequest<void>("DELETE", `/api/products/${encodeURIComponent(String(id))}`, {}, options);
}

/**
 * Search the catalog
 *
 * All filters are optional and combined with AND. Sortable by name, basePrice, createdAt, releaseDate and stockQuantity, e.g. `sort=basePrice,asc`.
 *
 * `GET /api/products` · Public.
 */
export function searchProducts(params?: SearchProductsParams, options?: RequestOptions): Promise<PageResponseProductResponse> {
  return apiRequest<PageResponseProductResponse>("GET", "/api/products", { query: params }, options);
}

/** `POST /api/products` · Requires a bearer token (`options.token`). Requires the ADMIN role. */
export function createProduct(body: ProductRequest, options?: RequestOptions): Promise<ProductResponse> {
  return apiRequest<ProductResponse>("POST", "/api/products", { body }, options);
}

/**
 * Get a product by slugs
 *
 * For product pages addressed by URL, e.g. `/pokemon/scarlet-violet-booster-box`.
 *
 * `GET /api/games/{gameSlug}/products/{productSlug}` · Public.
 */
export function getProductBySlug(gameSlug: string, productSlug: string, options?: RequestOptions): Promise<ProductResponse> {
  return apiRequest<ProductResponse>("GET", `/api/games/${encodeURIComponent(String(gameSlug))}/products/${encodeURIComponent(String(productSlug))}`, {}, options);
}

// ---- Payments ----

/**
 * Stripe webhook
 *
 * Called by Stripe, not by API clients; configure this URL in the Stripe dashboard for payment_intent.succeeded and payment_intent.canceled. Authenticated by the Stripe-Signature header (400 if invalid).
 *
 * `POST /api/payments/webhooks/stripe` · Public.
 */
export function handleStripeWebhook(body: string, headers: HandleStripeWebhookHeaders, options?: RequestOptions): Promise<void> {
  return apiRequest<void>("POST", "/api/payments/webhooks/stripe", { body, headers }, options);
}

/**
 * List the order's payment attempts
 *
 * `GET /api/orders/{orderId}/payments` · Requires a bearer token (`options.token`).
 */
export function listOrderPayments(orderId: number, options?: RequestOptions): Promise<PaymentResponse[]> {
  return apiRequest<PaymentResponse[]>("GET", `/api/orders/${encodeURIComponent(String(orderId))}/payments`, {}, options);
}

/**
 * Start paying an order
 *
 * Only for orders in PENDING_PAYMENT.
 * - **STRIPE:** confirm `stripeClientSecret` with Stripe.js; the order becomes PAID when Stripe's webhook arrives. Calling again returns the same PaymentIntent.
 * - **PAYPAL:** redirect the buyer to `payPalApprovalUrl`, then call the capture endpoint.
 *
 * `POST /api/orders/{orderId}/payments` · Requires a bearer token (`options.token`).
 */
export function startPayment(orderId: number, body: StartPaymentRequest, options?: RequestOptions): Promise<PaymentStartResponse> {
  return apiRequest<PaymentStartResponse>("POST", `/api/orders/${encodeURIComponent(String(orderId))}/payments`, { body }, options);
}

/**
 * Capture an approved PayPal payment
 *
 * Call after PayPal redirects the buyer back to the return URL. Returns the updated order.
 *
 * `POST /api/orders/{orderId}/payments/paypal/capture` · Requires a bearer token (`options.token`).
 */
export function capturePayPalPayment(orderId: number, body: CapturePayPalRequest, options?: RequestOptions): Promise<OrderResponse> {
  return apiRequest<OrderResponse>("POST", `/api/orders/${encodeURIComponent(String(orderId))}/payments/paypal/capture`, { body }, options);
}

// ---- Admin: pre-orders ----

/**
 * Release a pre-order product
 *
 * Stock has arrived: waiting items become READY_TO_SHIP and the product stops being a pre-order. Set the new stock level separately with `PUT /api/products/{id}`.
 *
 * `POST /api/admin/preorders/products/{productId}/release` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function releasePreorders(productId: number, options?: RequestOptions): Promise<PreorderReleaseResponse> {
  return apiRequest<PreorderReleaseResponse>("POST", `/api/admin/preorders/products/${encodeURIComponent(String(productId))}/release`, {}, options);
}

/**
 * Pre-order demand per product
 *
 * `GET /api/admin/preorders` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function listPreorderSummaries(options?: RequestOptions): Promise<PreorderSummaryResponse[]> {
  return apiRequest<PreorderSummaryResponse[]>("GET", "/api/admin/preorders", {}, options);
}

/**
 * Paid order items waiting for a product
 *
 * `GET /api/admin/preorders/products/{productId}` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function listPreorderItems(productId: number, options?: RequestOptions): Promise<PreorderItemResponse[]> {
  return apiRequest<PreorderItemResponse[]>("GET", `/api/admin/preorders/products/${encodeURIComponent(String(productId))}`, {}, options);
}

// ---- Admin: orders ----

/**
 * Correct a shipment's carrier or tracking number
 *
 * `PUT /api/admin/orders/{id}/shipments/{shipmentId}` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function updateShipment(id: number, shipmentId: number, body: UpdateShipmentRequest, options?: RequestOptions): Promise<OrderResponse> {
  return apiRequest<OrderResponse>("PUT", `/api/admin/orders/${encodeURIComponent(String(id))}/shipments/${encodeURIComponent(String(shipmentId))}`, { body }, options);
}

/**
 * Ship a parcel
 *
 * Ships READY_TO_SHIP items with a tracking number. Call again for pre-order items once they have been released.
 *
 * `POST /api/admin/orders/{id}/shipments` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function createShipment(id: number, body: CreateShipmentRequest, options?: RequestOptions): Promise<OrderResponse> {
  return apiRequest<OrderResponse>("POST", `/api/admin/orders/${encodeURIComponent(String(id))}/shipments`, { body }, options);
}

/**
 * Mark a shipment as delivered
 *
 * `POST /api/admin/orders/{id}/shipments/{shipmentId}/delivered` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function markShipmentDelivered(id: number, shipmentId: number, options?: RequestOptions): Promise<OrderResponse> {
  return apiRequest<OrderResponse>("POST", `/api/admin/orders/${encodeURIComponent(String(id))}/shipments/${encodeURIComponent(String(shipmentId))}/delivered`, {}, options);
}

/**
 * Cancel an order
 *
 * Allowed until the first item ships. Releases stock; paid orders are refunded automatically.
 *
 * `POST /api/admin/orders/{id}/cancel` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function cancelAdminOrder(id: number, options?: RequestOptions): Promise<OrderResponse> {
  return apiRequest<OrderResponse>("POST", `/api/admin/orders/${encodeURIComponent(String(id))}/cancel`, {}, options);
}

/**
 * Search orders
 *
 * Sortable by createdAt, paidAt, totalAmount and status.
 *
 * `GET /api/admin/orders` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function searchAdminOrders(params?: SearchAdminOrdersParams, options?: RequestOptions): Promise<PageResponseOrderSummaryResponse> {
  return apiRequest<PageResponseOrderSummaryResponse>("GET", "/api/admin/orders", { query: params }, options);
}

/**
 * List an order's payment attempts
 *
 * Includes refunds that failed (REFUND_FAILED) and must be handled manually in the provider dashboard.
 *
 * `GET /api/admin/orders/{orderId}/payments` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function listAdminOrderPayments(orderId: number, options?: RequestOptions): Promise<PaymentResponse[]> {
  return apiRequest<PaymentResponse[]>("GET", `/api/admin/orders/${encodeURIComponent(String(orderId))}/payments`, {}, options);
}

/** `GET /api/admin/orders/{id}` · Requires a bearer token (`options.token`). Requires the ADMIN role. */
export function getAdminOrder(id: number, options?: RequestOptions): Promise<OrderResponse> {
  return apiRequest<OrderResponse>("GET", `/api/admin/orders/${encodeURIComponent(String(id))}`, {}, options);
}

// ---- Admin: shipping rates ----

/**
 * Create or replace a country's shipping rate
 *
 * `PUT /api/admin/shipping-rates/{country}` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function upsertShippingRate(country: "AT" | "BE" | "BG" | "HR" | "CY" | "CZ" | "DK" | "EE" | "FI" | "FR" | "DE" | "GR" | "HU" | "IE" | "IT" | "LV" | "LT" | "LU" | "MT" | "NL" | "PL" | "PT" | "RO" | "SK" | "SI" | "ES" | "SE", body: ShippingRateRequest, options?: RequestOptions): Promise<ShippingRateResponse> {
  return apiRequest<ShippingRateResponse>("PUT", `/api/admin/shipping-rates/${encodeURIComponent(String(country))}`, { body }, options);
}

/**
 * Stop shipping to a country
 *
 * `DELETE /api/admin/shipping-rates/{country}` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function deleteShippingRate(country: "AT" | "BE" | "BG" | "HR" | "CY" | "CZ" | "DK" | "EE" | "FI" | "FR" | "DE" | "GR" | "HU" | "IE" | "IT" | "LV" | "LT" | "LU" | "MT" | "NL" | "PL" | "PT" | "RO" | "SK" | "SI" | "ES" | "SE", options?: RequestOptions): Promise<void> {
  return apiRequest<void>("DELETE", `/api/admin/shipping-rates/${encodeURIComponent(String(country))}`, {}, options);
}

// ---- Admin: overview ----

/**
 * Sales and inventory overview
 *
 * Revenue counts paid orders that were not cancelled afterwards. "Today" uses the configured reporting time zone (Europe/Berlin by default).
 *
 * `GET /api/admin/overview` · Requires a bearer token (`options.token`). Requires the ADMIN role.
 */
export function getAdminOverview(options?: RequestOptions): Promise<AdminOverviewResponse> {
  return apiRequest<AdminOverviewResponse>("GET", "/api/admin/overview", {}, options);
}
